export const INITIAL_VEHICLES: any[] = [
  {
    id: '1',
    vin: 'WDD2221761AXXXXXX',
    make: 'Mercedes-Benz',
    model: 'S580',
    year: 2023,
    price: 28500000,
    image: 'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?q=80&w=800&auto=format&fit=crop',
    color: 'Obsidian Black',
    transmission: 'Automatic',
    fuelType: 'Petrol',
    engine: '4.0L V8 BiTurbo',
    status: 'Available',
    slug: '2023-mercedes-benz-s580',
    description: 'The Mercedes-Benz S580 represents the ultimate in refinement, offering quiet operations, an absolute masterclass of technological options, and twin-turbocharged performance for Nairobi executives.',
    inquiriesCount: 8,
    mileage: 8500,
    trim: 'Maybach Line'
  },
  {
    id: '2',
    vin: 'WBA81EM080GXXXXXX',
    make: 'BMW',
    model: 'X7 M50i',
    year: 2022,
    price: 19200000,
    image: 'https://images.unsplash.com/photo-1555215695-3004980ad54e?q=80&w=800&auto=format&fit=crop',
    color: 'Mineral White',
    transmission: 'Automatic',
    fuelType: 'Petrol',
    engine: '4.4L TwinPower V8',
    status: 'Reserved',
    slug: '2022-bmw-x7-m50i',
    description: 'Brimming with visual dominance and technical excellence, this triple-row luxury cruiser delivers unparalleled dynamic precision under the Kenyan skies.',
    inquiriesCount: 4,
    mileage: 18200,
    trim: 'M Sport'
  },
  {
    id: '3',
    vin: 'SALLHREF2LAXXXXXX',
    make: 'Land Rover',
    model: 'Range Rover Autobiography',
    year: 2021,
    price: 22000000,
    image: 'https://images.unsplash.com/photo-1608754519398-e3f5d5402652?q=80&w=800&auto=format&fit=crop',
    color: 'Portofino Blue',
    transmission: 'Automatic',
    fuelType: 'Petrol',
    engine: '5.0L Supercharged V8',
    status: 'Sold',
    slug: '2021-range-rover-autobiography',
    description: 'An immaculate specimen in Portofino Blue. Features executive rear airline seats, absolute comfort tuning, and powerful supercharged capabilities.',
    inquiriesCount: 6,
    mileage: 24000,
    trim: 'Autobiography'
  },
  {
    id: '4',
    vin: 'WP0ZZZ99ZLSXXXXXX',
    make: 'Porsche',
    model: '911 Turbo S',
    year: 2024,
    price: 42000000,
    image: 'https://images.unsplash.com/photo-1614162692292-7ac56d7f7f1e?q=80&w=800&auto=format&fit=crop',
    color: 'GT Silver',
    transmission: 'PDK',
    fuelType: 'Petrol',
    engine: '3.8L Twin-Turbo Flat-6',
    status: 'Available',
    slug: '2024-porsche-911-turbo-s',
    description: 'The definitive executive daily pilot. Unleashes staggering acceleration and track performance while remaining perfectly refined inside Nairobi traffic.',
    inquiriesCount: 14,
    mileage: 1200,
    trim: 'Turbo S'
  },
  {
    id: '5',
    vin: 'ZFF81NHA000XXXXXX',
    make: 'Ferrari',
    model: 'F8 Tributo',
    year: 2023,
    price: 58000000,
    image: 'https://images.unsplash.com/photo-1583121274602-3e2820c69888?q=80&w=800&auto=format&fit=crop',
    color: 'Nero Aldebaran',
    transmission: 'Automatic',
    fuelType: 'Petrol',
    engine: '3.9L Twin-Turbo V8',
    status: 'Available',
    slug: '2023-ferrari-f8-tributo',
    description: 'An aggressive, beautiful mid-engine masterpiece honoring Ferrari\'s finest V8 lineage. Offers mind-bending mechanics and precise aerodynamics.',
    inquiriesCount: 12,
    mileage: 3400,
    trim: 'Tributo'
  },
  {
    id: '6',
    vin: 'W1Y4G7HB2LAXXXXXX',
    make: 'Mercedes-Benz',
    model: 'AMG G63',
    year: 2023,
    price: 34000000,
    image: 'https://images.unsplash.com/photo-1520050206274-a1ae446cb3cc?q=80&w=800&auto=format&fit=crop',
    color: 'Designo Magno Platinum',
    transmission: 'Automatic',
    fuelType: 'Petrol',
    engine: '4.0L V8 Biturbo',
    status: 'Available',
    slug: '2023-mercedes-benz-amg-g63',
    description: 'The ultimate symbol of off-road dominance and absolute road prestige. Finished in highly sought-after satin matte Designo Magno Platinum with carbon fibre trim.',
    inquiriesCount: 22,
    mileage: 5100,
    trim: 'Edition 55'
  },
  {
    id: '7',
    vin: 'WBS53AY000FXXXXXX',
    make: 'BMW',
    model: 'M3 Competition',
    year: 2023,
    price: 16500000,
    image: 'https://images.unsplash.com/photo-1617531653332-bd46c24f2068?q=80&w=800&auto=format&fit=crop',
    color: 'Isle of Man Green',
    transmission: 'Automatic',
    fuelType: 'Petrol',
    engine: '3.0L TwinPower Turbo I6',
    status: 'Available',
    slug: '2023-bmw-m3-competition',
    description: 'A sports sedan icon. Outfitted in head-turning Isle of Man Green metallic with Kyoto Orange Merino leather interior. Unparalleled dynamic responses.',
    inquiriesCount: 9,
    mileage: 9300,
    trim: 'Competition xDrive'
  },
  {
    id: '8',
    vin: 'WA1URCFD4MAXXXXXX',
    make: 'Audi',
    model: 'RSQ8',
    year: 2022,
    price: 21500000,
    image: 'https://images.unsplash.com/photo-1606016159991-dfe4f2746ad5?q=80&w=800&auto=format&fit=crop',
    color: 'Nardo Grey',
    transmission: 'Automatic',
    fuelType: 'Petrol',
    engine: '4.0L V8 Twin-Turbo',
    status: 'Available',
    slug: '2022-audi-rsq8',
    description: 'The pinnacle of Audi Sport SUV capabilities. Merges supercar performance with premium SUV utility. Wrapped in iconic Nardo Grey with black optics package.',
    inquiriesCount: 15,
    mileage: 14500,
    trim: 'Carbon Black Edition'
  },
  {
    id: '9',
    vin: 'WP0AB2Y11LAXXXXXX',
    make: 'Porsche',
    model: 'Taycan Turbo S',
    year: 2023,
    price: 26000000,
    image: 'https://images.unsplash.com/photo-1611245801319-41712a831e53?q=80&w=800&auto=format&fit=crop',
    color: 'Mamba Green Metallic',
    transmission: 'Automatic',
    fuelType: 'Electric',
    engine: 'Dual Electric Motors (750hp)',
    status: 'Available',
    slug: '2023-porsche-taycan-turbo-s',
    description: 'Bespoke electric sport luxury. Delivers instantaneous, silent acceleration, innovative cockpit screens, and Stuttgart\'s legendary handling dynamics.',
    inquiriesCount: 5,
    mileage: 4600,
    trim: 'Turbo S'
  },
  {
    id: '10',
    vin: 'SALHB4EU3LAXXXXXX',
    make: 'Land Rover',
    model: 'Defender 110 V8',
    year: 2023,
    price: 22500000,
    image: 'https://images.unsplash.com/photo-1609521263047-f8f205293f24?q=80&w=800&auto=format&fit=crop',
    color: 'Carpathian Grey',
    transmission: 'Automatic',
    fuelType: 'Petrol',
    engine: '5.0L Supercharged V8',
    status: 'Available',
    slug: '2023-land-rover-defender-110-v8',
    description: 'A legendary rugged structure supercharged. Combines unstoppable off-road mechanical components with a roaring 518hp V8 power plant.',
    inquiriesCount: 11,
    mileage: 7800,
    trim: 'Carpathian Edition'
  },
  {
    id: '11',
    vin: 'JTJHY7BL2NAXXXXXX',
    make: 'Lexus',
    model: 'LX 600',
    year: 2023,
    price: 29800000,
    image: 'https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?q=80&w=800&auto=format&fit=crop',
    color: 'Eminent White Pearl',
    transmission: 'Automatic',
    fuelType: 'Petrol',
    engine: '3.4L Twin-Turbo V6',
    status: 'Available',
    slug: '2023-lexus-lx-600',
    description: 'The definitive high-ticket luxury cruiser, offering unmatched reliability and prestige in the East African market. Fully optioned VIP executive cabin layout.',
    inquiriesCount: 19,
    mileage: 6200,
    trim: 'Ultra Luxury'
  },
  {
    id: '12',
    vin: 'SCBGB7ZA0MAXXXXXX',
    make: 'Bentley',
    model: 'Continental GT',
    year: 2022,
    price: 36500000,
    image: 'https://images.unsplash.com/photo-1621135802920-133df287f89c?q=80&w=800&auto=format&fit=crop',
    color: 'Monaco Yellow',
    transmission: 'Automatic',
    fuelType: 'Petrol',
    engine: '6.0L Twin-Turbo W12',
    status: 'Reserved',
    slug: '2022-bentley-continental-gt',
    description: 'A grand touring masterpiece. Exquisite handcrafted leather upholstery, rotating display dashboard, and an effortless 626hp surge of power.',
    inquiriesCount: 7,
    mileage: 11500,
    trim: 'Mulliner Spec'
  },
  {
    id: '13',
    vin: 'SADAG33Y0LAXXXXXX',
    make: 'Aston Martin',
    model: 'Vantage',
    year: 2021,
    price: 18500000,
    image: 'https://images.unsplash.com/photo-1617814076367-b759c7d7e738?q=80&w=800&auto=format&fit=crop',
    color: 'British Racing Green',
    transmission: 'Automatic',
    fuelType: 'Petrol',
    engine: '4.0L Twin-Turbo V8',
    status: 'Available',
    slug: '2021-aston-martin-vantage',
    description: 'Sculptured British aerodynamics coupled with AMG V8 mechanics. Beautiful sports chassis design, carbon ceramic stopping units, and active track settings.',
    inquiriesCount: 4,
    mileage: 15300,
    trim: 'F1 Edition'
  },
  {
    id: '14',
    vin: 'WUAZZZ4S0LAXXXXXX',
    make: 'Audi',
    model: 'R8 V10 Performance',
    year: 2022,
    price: 32000000,
    image: 'https://images.unsplash.com/photo-1603584173870-7f23fdae1b7a?q=80&w=800&auto=format&fit=crop',
    color: 'Kemora Grey',
    transmission: 'Automatic',
    fuelType: 'Petrol',
    engine: '5.2L Naturally Aspirated V10',
    status: 'Sold',
    slug: '2022-audi-r8-v10-performance',
    description: 'The final generation of a naturally-aspirated V10 legend. Direct mechanical kin to the Huracán, featuring Quattro stability and premium cabin options.',
    inquiriesCount: 16,
    mileage: 8200,
    trim: 'Decennium Edition'
  },
  {
    id: '15',
    vin: 'W1KZH8GB6LAXXXXXX',
    make: 'Mercedes-Benz',
    model: 'AMG E63 S',
    year: 2022,
    price: 17800000,
    image: 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?q=80&w=800&auto=format&fit=crop',
    color: 'Graphite Grey Metallic',
    transmission: 'Automatic',
    fuelType: 'Petrol',
    engine: '4.0L V8 Biturbo',
    status: 'Available',
    slug: '2022-mercedes-benz-amg-e63-s',
    description: 'A executive missile. Offers supercar-slaying straight line speed, dual suspension modes, drift-mode capabilities, and luxury rear massage cabin.',
    inquiriesCount: 8,
    mileage: 16900,
    trim: 'Final Edition'
  },
  {
    id: '16',
    vin: 'WBSDZ9C06NAXXXXXX',
    make: 'BMW',
    model: 'M8 Competition',
    year: 2023,
    price: 24500000,
    image: 'https://images.unsplash.com/photo-1580273916550-e323be2ae537?q=80&w=800&auto=format&fit=crop',
    color: 'Marina Bay Blue',
    transmission: 'Automatic',
    fuelType: 'Petrol',
    engine: '4.4L TwinPower V8',
    status: 'Available',
    slug: '2023-bmw-m8-competition',
    description: 'The luxury grand tourer benchmark. Blends premium carbon interior architecture, M xDrive versatility, and a staggering 617 horsepower output.',
    inquiriesCount: 10,
    mileage: 4200,
    trim: 'Competition Gran Coupe'
  },
  {
    id: '17',
    vin: 'W1N253D32MAXXXXXX',
    make: 'Mercedes-Benz',
    model: 'GLE 53 AMG',
    year: 2023,
    price: 19800000,
    image: 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?q=80&w=800&auto=format&fit=crop',
    color: 'Selena Grey Metallic',
    transmission: 'Automatic',
    fuelType: 'Petrol',
    engine: '3.0L Turbo Inline-6 (Mild Hybrid)',
    status: 'Available',
    slug: '2023-mercedes-benz-gle-53-amg',
    description: 'Seamlessly blends athletic road performance with everyday luxury. Features active exhaust system, panoramic roof, and digital infotainment setup.',
    inquiriesCount: 13,
    mileage: 11000,
    trim: 'AMG Coupe'
  },
  {
    id: '18',
    vin: 'SALWR2BV3LAXXXXXX',
    make: 'Land Rover',
    model: 'Range Rover Sport SVR',
    year: 2021,
    price: 16800000,
    image: 'https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?q=80&w=800&auto=format&fit=crop',
    color: 'Estoril Blue',
    transmission: 'Automatic',
    fuelType: 'Petrol',
    engine: '5.0L Supercharged V8',
    status: 'Available',
    slug: '2021-range-rover-sport-svr',
    description: 'The loudest and fastest Range Rover Sport. Outfitted with carbon fibre hood vents, dual active exhaust, and performance sports bucket seats.',
    inquiriesCount: 18,
    mileage: 22000,
    trim: 'SVR Carbon Edition'
  },
  {
    id: '19',
    vin: 'WP0ZZZ9Y0NAXXXXXX',
    make: 'Porsche',
    model: 'Cayenne Turbo GT',
    year: 2023,
    price: 38000000,
    image: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?q=80&w=800&auto=format&fit=crop',
    color: 'Arctic Grey',
    transmission: 'Automatic',
    fuelType: 'Petrol',
    engine: '4.0L Twin-Turbo V8',
    status: 'Available',
    slug: '2023-porsche-cayenne-turbo-gt',
    description: 'The quickest SUV around the Nürburgring. Carbon-ceramic stopping units, titanium exhaust pipes, and extreme Stuttgart engineering tailored for the elite.',
    inquiriesCount: 14,
    mileage: 3800,
    trim: 'Turbo GT Coupe'
  },
  {
    id: '20',
    vin: 'WUAZZZ4G0MAXXXXXX',
    make: 'Audi',
    model: 'RS6 Avant',
    year: 2022,
    price: 19500000,
    image: 'https://images.unsplash.com/photo-1609521263047-f8f205293f24?q=80&w=800&auto=format&fit=crop',
    color: 'Sebring Black Crystal',
    transmission: 'Automatic',
    fuelType: 'Petrol',
    engine: '4.0L V8 Twin-Turbo (Mild Hybrid)',
    status: 'Available',
    slug: '2022-audi-rs6-avant',
    description: 'The ultimate super-wagon. Combines raw, drag-strip destroying speed with immense family practicality and high-tech digital cockpits.',
    inquiriesCount: 11,
    mileage: 17400,
    trim: 'Vorsprung Edition'
  },
  {
    id: '21',
    vin: 'JTJZA1BL9MAXXXXXX',
    make: 'Lexus',
    model: 'RX 350',
    year: 2022,
    price: 9800000,
    image: 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?q=80&w=800&auto=format&fit=crop',
    color: 'Caviar Black',
    transmission: 'Automatic',
    fuelType: 'Petrol',
    engine: '3.5L V6',
    status: 'Available',
    slug: '2022-lexus-rx-350-f-sport',
    description: 'The staple of comfort and reliability. Outfitted with Lexus safety systems, dark mesh grille design, and red sports leather cabin.',
    inquiriesCount: 9,
    mileage: 32000,
    trim: 'F-Sport Series 3'
  },
  {
    id: '22',
    vin: 'WBS21EJ080HXXXXXX',
    make: 'BMW',
    model: 'i7 xDrive60',
    year: 2023,
    price: 27500000,
    image: 'https://images.unsplash.com/photo-1525609004556-c46c7d6cf0a3?q=80&w=800&auto=format&fit=crop',
    color: 'Oxide Grey Metallic',
    transmission: 'Automatic',
    fuelType: 'Electric',
    engine: 'Dual Electric Motors (536hp)',
    status: 'Available',
    slug: '2023-bmw-i7-xdrive60',
    description: 'Next-generation luxury. Feeds passenger passengers a massive 31.3-inch rear theater screen, premium sound insulation, and zero tailpipe emissions.',
    inquiriesCount: 6,
    mileage: 2100,
    trim: 'M Sport Excellence'
  },
  {
    id: '23',
    vin: 'WDC3229761AXXXXXX',
    make: 'Mercedes-Benz',
    model: 'GLS 600 Maybach',
    year: 2023,
    price: 38500000,
    image: 'https://images.unsplash.com/photo-1511919884226-fd3cad34687c?q=80&w=800&auto=format&fit=crop',
    color: 'Duo-tone Rubellite Red / Kalahari Gold',
    transmission: 'Automatic',
    fuelType: 'Petrol',
    engine: '4.0L V8 Biturbo',
    status: 'Reserved',
    slug: '2023-mercedes-benz-gls-600-maybach',
    description: 'First-class luxury travel redefined. Dual reclining rear passenger lounges, active air fragrance dispersion, and pneumatic refrigerator console.',
    inquiriesCount: 16,
    mileage: 4800,
    trim: 'Maybach VIP Edition'
  },
  {
    id: '24',
    vin: 'WP0ZZZ97ZLAXXXXXX',
    make: 'Porsche',
    model: 'Panamera GTS',
    year: 2022,
    price: 19800000,
    image: 'https://images.unsplash.com/photo-1614162692292-7ac56d7f7f1e?q=80&w=800&auto=format&fit=crop',
    color: 'Carmine Red',
    transmission: 'PDK',
    fuelType: 'Petrol',
    engine: '4.0L Twin-Turbo V8',
    status: 'Available',
    slug: '2022-porsche-panamera-gts',
    description: 'Four-door performance sedan blending race car pedigree with executive space. Carbon fiber options, Alcantara cockpit finish, and active sport aero spoiler.',
    inquiriesCount: 5,
    mileage: 16200,
    trim: 'GTS Sport'
  },
  {
    id: '25',
    vin: 'SALHB4DU1LAXXXXXX',
    make: 'Land Rover',
    model: 'Defender 90',
    year: 2022,
    price: 14500000,
    image: 'https://images.unsplash.com/photo-1609521263047-f8f205293f24?q=80&w=800&auto=format&fit=crop',
    color: 'Tasman Blue Metallic',
    transmission: 'Automatic',
    fuelType: 'Diesel',
    engine: '3.0L MHEV I6 Turbo Diesel',
    status: 'Available',
    slug: '2022-land-rover-defender-90-d300',
    description: 'Short-wheelbase explorer. High torque diesel capabilities, premium cabin options, and legendary capability for weekend escapes in Naivasha.',
    inquiriesCount: 12,
    mileage: 18900,
    trim: 'SE D300'
  },
  {
    id: '26',
    vin: 'WUAZZZFW2MAXXXXXX',
    make: 'Audi',
    model: 'e-tron GT',
    year: 2023,
    price: 21000000,
    image: 'https://images.unsplash.com/photo-1617531653332-bd46c24f2068?q=80&w=800&auto=format&fit=crop',
    color: 'Ascari Blue Metallic',
    transmission: 'Automatic',
    fuelType: 'Electric',
    engine: 'Dual Electric Motors (522hp)',
    status: 'Available',
    slug: '2023-audi-e-tron-gt',
    description: 'Sleek, aerodynamic German design sharing its underpinnings with the Porsche Taycan. Luxury acoustics and instantaneous quattro torque response.',
    inquiriesCount: 7,
    mileage: 3800,
    trim: 'Premium Plus'
  },
  {
    id: '27',
    vin: 'SADAG99B2LAXXXXXX',
    make: 'Lamborghini',
    model: 'Urus',
    year: 2022,
    price: 45000000,
    image: 'https://images.unsplash.com/photo-1606016159991-dfe4f2746ad5?q=80&w=800&auto=format&fit=crop',
    color: 'Giallo Auge (Yellow)',
    transmission: 'Automatic',
    fuelType: 'Petrol',
    engine: '4.0L Twin-Turbo V8',
    status: 'Available',
    slug: '2022-lamborghini-urus',
    description: 'The definitive super-SUV. Unparalleled racetrack aggression packaged in a luxurious everyday chassis. Finished in Lambo\'s signature Giallo Auge.',
    inquiriesCount: 29,
    mileage: 9100,
    trim: 'V8 Performance'
  },
  {
    id: '28',
    vin: 'ZHW28NHA9MAXXXXXX',
    make: 'Maserati',
    model: 'MC20',
    year: 2023,
    price: 39500000,
    image: 'https://images.unsplash.com/photo-1603584173870-7f23fdae1b7a?q=80&w=800&auto=format&fit=crop',
    color: 'Bianco Audace (Satin White)',
    transmission: 'Automatic',
    fuelType: 'Petrol',
    engine: '3.0L Twin-Turbo V6 Nettuno',
    status: 'Available',
    slug: '2023-maserati-mc20',
    description: 'Exquisite Italian carbon-monocoque performance. Outfitted with Maserati\'s proprietary F1-derived Nettuno engine producing a blistering 621hp.',
    inquiriesCount: 6,
    mileage: 1200,
    trim: 'Nettuno Coupe'
  },
  {
    id: '29',
    vin: 'ZFF88BHA2NAXXXXXX',
    make: 'Ferrari',
    model: '296 GTB',
    year: 2023,
    price: 49000000,
    image: 'https://images.unsplash.com/photo-1583121274602-3e2820c69888?q=80&w=800&auto=format&fit=crop',
    color: 'Rosso Corsa',
    transmission: 'Automatic',
    fuelType: 'Petrol',
    engine: '3.0L V6 Twin-Turbo Plug-In Hybrid',
    status: 'Sold',
    slug: '2023-ferrari-296-gtb',
    description: 'The defining hybrid performance marvel from Maranello. Combines a screaming V6 with electric assist to output 819 horsepower. Pristine Rosso Corsa.',
    inquiriesCount: 14,
    mileage: 2600,
    trim: 'Assetto Fiorano'
  },
  {
    id: '30',
    vin: 'WBS21EH040JXXXXXX',
    make: 'BMW',
    model: 'M5 CS',
    year: 2022,
    price: 23500000,
    image: 'https://images.unsplash.com/photo-1555215695-3004980ad54e?q=80&w=800&auto=format&fit=crop',
    color: 'Frozen Deep Green Metallic',
    transmission: 'Automatic',
    fuelType: 'Petrol',
    engine: '4.4L TwinPower V8',
    status: 'Available',
    slug: '2022-bmw-m5-cs',
    description: 'The most powerful road car in BMW history. Extreme carbon track weight reduction, 4 bucket seats, gold bronze wheels and accents. Collector spec.',
    inquiriesCount: 17,
    mileage: 5400,
    trim: 'CS Limited'
  }
];

export const INITIAL_INQUIRIES: any[] = [
  {
    id: 'inq-1',
    clientName: 'Kamau Maina',
    clientInitials: 'KM',
    vehicleName: 'Mercedes-AMG G63',
    date: 'Today, 10:45 AM',
    status: 'New',
    email: 'k.maina@exclusive-investments.co.ke',
    phone: '+254 722 000 111',
    notes: 'Inquired through web portal regarding trade-in options for a 2019 Range Rover. Prefers dynamic dark titanium styling.'
  },
  {
    id: 'inq-2',
    clientName: 'Amina Otieno',
    clientInitials: 'AO',
    vehicleName: 'Range Rover Autobiography',
    date: 'Yesterday',
    status: 'Contacted',
    email: 'amina.otieno@royaldevelopments.com',
    phone: '+254 733 444 555',
    notes: 'Scheduled high-profile private viewing at the showroom this coming Friday, 4:00 PM. Interested in bulletproofing options.'
  },
  {
    id: 'inq-3',
    clientName: 'Samuel Njau',
    clientInitials: 'SN',
    vehicleName: 'BMW M8 Competition',
    date: '2 days ago',
    status: 'New',
    email: 'snjau.advocates@safari.net',
    phone: '+254 711 777 999',
    notes: 'Inquiry specifically on lease terms and corporate tax structures under asset financing. Requested brochure.'
  },
  {
    id: 'inq-4',
    clientName: 'Esther Wanjiku',
    clientInitials: 'EW',
    vehicleName: 'Porsche 911 Turbo S',
    date: '2 days ago',
    status: 'Contacted',
    email: 'esther@wanjikuholdings.co.ke',
    phone: '+254 724 888 222',
    notes: 'Test-drive completed yesterday around Limuru Road. Commended PDK speed but wants optional carbon brakes option.'
  },
  {
    id: 'inq-5',
    clientName: 'James Kiptoo',
    clientInitials: 'JK',
    vehicleName: 'Toyota Land Cruiser LC300',
    date: '3 days ago',
    status: 'New',
    email: 'kiptoo.j@riftvalley-exports.com',
    phone: '+254 701 333 444',
    notes: 'Looking to purchase 2 identical units for regional ranch touring operations. Demanded cash payment discount structure.'
  }
];
